# Generated by Django 4.1.7 on 2023-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_customer_category_total_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_spend',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
