# Generated by Django 4.1.7 on 2023-04-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_color_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_spend',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
