# Generated by Django 4.1.7 on 2023-04-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_total_spend_alter_purchase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_spend',
            field=models.FloatField(default=0, null=True),
        ),
    ]
