# Generated by Django 4.1.7 on 2023-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_total_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spended_sum',
            field=models.FloatField(default=0),
        ),
    ]
